{
 "title": "Elixir Strategies",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Avellaneda Stoikov", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Best Ask",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    { "expr": "avellaneda_stoikov_best_ask", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Inventory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "targets": [
    { "expr": "avellaneda_stoikov_inventory", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Volatility",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "targets": [
    { "expr": "avellaneda_stoikov_vol", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Reservation Price",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "avellaneda_stoikov_reservation_price",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Optimal Ask",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "targets": [
    { "expr": "avellaneda_stoikov_optimal_ask", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Optimal Bid",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "targets": [
    { "expr": "avellaneda_stoikov_optimal_bid", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Optimal Spread",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "avellaneda_stoikov_optimal_spread",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mid Price",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "targets": [
    { "expr": "avellaneda_stoikov_mid_price", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Min Limit Ask",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "avellaneda_stoikov_min_limit_ask",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Min Spread",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "targets": [
    { "expr": "avellaneda_stoikov_min_spread", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Max Limit Bid",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "avellaneda_stoikov_max_limit_bid",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alpha",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
   "targets": [
    { "expr": "avellaneda_stoikov_alpha", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Gamma",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 25 },
   "targets": [
    { "expr": "avellaneda_stoikov_gamma", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Kapppa",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 25 },
   "targets": [
    { "expr": "avellaneda_stoikov_kappa", "legendFormat": "__auto" }
   ]
  }
 ]
}