apiVersion: apps/v1
kind: Deployment
metadata:
  name: elixir-validator
  labels:
    app: elixir
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elixir
  template:
    metadata:
      labels:
        app: elixir
    spec:
      containers:
      - name: elixir-validator
        image: elixirprotocol/validator:testnet-1
          env:
            - name: ADDRESS
              value: ""
            - name: PRIVATE_KEY
              value: ""

